### ISSUE TITLE
Doc builds failing

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#101]
The doc builds are currently failing. Apparently due to some error when importing Pandas.
```
Running Sphinx v1.5.6
making output directory...
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 22, in <module>
    import radvel
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/radvel-1.0.1-py2.7-linux-x86_64.egg/radvel/__init__.py", line 1, in <module>
    from .model import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/radvel-1.0.1-py2.7-linux-x86_64.egg/radvel/model.py", line 6, in <module>
    from radvel.basis import Basis
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/radvel-1.0.1-py2.7-linux-x86_64.egg/radvel/basis.py", line 2, in <module>
    import pandas as pd
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/radvel/envs/stable/local/lib/python2.7/site-packages/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
The full traceback has been saved in /tmp/sphinx-err-90VfrI.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>.
```

**Comment by petigura** [comment]
This error may have something to do with the fact that sphinx is trying to import the numpy module which is throwing some compile-build errors. I think @samuelyeewl, ran into this when doc'ing specmatch-emp. This is a silly error because RTD doesn't need the numpy modules to build the docs. I think you can fake it by importing a "mock" numpy module into sphinx:

http://blog.rtwilson.com/how-to-make-your-sphinx-documentation-compile-with-readthedocs-when-youre-using-numpy-and-scipy/

**Comment by bjfultn** [comment]
I feel like something must have changed on RTD since it was working fine before and then all of the sudden stopped working without changing the parts of the code that it was complaining about. Regardless, I was able to fix the problem by adding the following code to the top of `conf.py` before the `import radvel` call and changing the format of a couple imports elsewhere.

```
autodoc_mock_imports = ['_tkinter', 'pandas', 'scipy.optimize']
for mod_name in autodoc_mock_imports:
    sys.modules[mod_name] = mock.Mock()
```

**Comment by petigura** [comment]
I think there probably was some version of numpy that was correctly compiled, but some version on their end must have been bumped, so the numpy C code is different from what the python module expects. Regardless, there is no reason for sphinx to touch any of the modules that are not referenced explicitly in the docs so I think your new way is the way to go.

```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
```
