### ISSUE TITLE
report failing w/ tp basis; 'tc' key error

### ISSUE THREAD

**Issue by sealauren** [California-Planet-Search/radvel#129]
radvel report -s ******.py
******.py
Assembling report for ******
WARNING: Could not find nplanets BIC model comparisonin ./******/******_radvel.stat.
Please make sure that you have run `radvel bic -t nplanets` if you wouldlike to include
the model comparison table in the report.
Traceback (most recent call last):
  File "/Users/lweiss/anaconda/bin/radvel", line 11, in <module>
    load_entry_point('radvel==1.1.0', 'console_scripts', 'radvel')()
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/cli.py", line 172, in main
    args.func(args)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/driver.py", line 443, in report
    rfile, depfiles=report_depfiles, latex_compiler=args.latex_compiler
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 173, in compile
    f.write(self.texdoc())
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 94, in texdoc
    out = self._preamble() + self.tabletex()
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 110, in tabletex
    return TexTable(self).tex(tabtype=tabtype)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 339, in tex
    sidehead='\\bf{Other Parameters}', hline=True)+\
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 284, in _data
    tabledat += self._row(p, unit)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel-1.1.0-py2.7-macosx-10.6-x86_64.egg/radvel/report.py", line 235, in _row
    med = self.quantiles[param][0.5]
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'tc'

**Comment by bjfultn** [comment]
Assigning to @sealauren to see if implementing both the `to_synth` and `from_synth` methods for the new basis will fix this. If not, please assign back to me.

**Comment by bjfultn** [comment]
I can confirm that report compilation works fine using the `logper tp e w logk` basis without error. I'm closing this issue for now. @sealauren please re-open if you see this error again.
