### ISSUE TITLE
Travis CI builds failing for Python 2.7

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#140]
Travis builds seem to suddenly be failing without changing anything I can think of that would produce the error:
```
======================================================================
ERROR: Failure: ImportError (cannot import name configparser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/California-Planet-Search/radvel/radvel/tests/test_nb.py", line 8, in <module>
    from nbconvert.preprocessors import ExecutePreprocessor
  File "/home/travis/miniconda/lib/python2.7/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/travis/miniconda/lib/python2.7/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
    from .base import (export, get_exporter,
  File "/home/travis/miniconda/lib/python2.7/site-packages/nbconvert/exporters/base.py", line 8, in <module>
    import entrypoints
  File "/home/travis/miniconda/lib/python2.7/site-packages/entrypoints.py", line 19, in <module>
    from backports import configparser
ImportError: cannot import name configparser
```

I've been trying to figure this out for a couple days now and am not having much success. Has anyone else seen such an issue on their local machine or when working with Travis?

**Comment by bjfultn** [comment]
Found a solution thanks to what I read here: https://github.com/takluyver/entrypoints/issues/3

I added a specific version for `configparser` in the `conda install` call in `.travis.yml`: `configparser==3.5.0b2`

**Comment by bjfultn** [comment]
Except that this solution broke the Python 3 tests. I added an if statement to only install `configparser==3.5.0b2` if testing in Python 2.
