### ISSUE TITLE
radvel report crashes when instrument name has an underscore

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/radvel#219]
For example, if my RV data set is defined by:
```
rv_columns = ['time', 'mnvel', 'errvel', 'tel']

rv_data = [ 
           [2455487.025885, -2.668606, 0.923656, 'hires_j'],
           [2455487.026776, -0.881930, 0.946263, 'hires_j'],
           [2455487.027679, -1.594348, 0.922529, 'hires_j'],
           [2455500.988923, -4.846509, 0.839449, 'hires_j'],
           [2455500.989802, -6.066212, 0.830558, 'hires_j'],
           [2455500.990682, -5.827422, 0.940917, 'hires_j'],
           [2455521.867163, -1.020171, 0.950976, 'hires_j']
          ]

data = pd.DataFrame(data=rv_data,
                    columns=rv_columns)
```
then, after a fit (and MCMC) the command
```
radvel report -s file.py 
```
will fail in report.py in lines 146-153, without reaching the except statement, since the failure is caused by the latex compiler waiting for a command (since the .tex file has bad syntax due to unescaped/dollar-signed underscores).

**Comment by smmills** [comment]
This will sometimes cause the next line in report.py to fail (see below), or sometimes just hang for a really long time
```
Traceback (most recent call last):
  File "/Users/seanmills/radvel_process/radvel_process_env/bin/radvel", line 11, in <module>
    sys.exit(main())
  File "/Users/seanmills/radvel_process/radvel_process_env/lib/python3.7/site-packages/radvel/cli.py", line 171, in main
    args.func(args)
  File "/Users/seanmills/radvel_process/radvel_process_env/lib/python3.7/site-packages/radvel/driver.py", line 526, in report
    rfile, depfiles=report_depfiles, latex_compiler=args.latex_compiler
  File "/Users/seanmills/radvel_process/radvel_process_env/lib/python3.7/site-packages/radvel/report.py", line 162, in compile
    shutil.copy(pdfname, current)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'default_results.pdf'
```

**Comment by bjfultn** [comment]
Are you sure this is caused by the instrument names? I just modified the HD 164922 example and replaced the 'j' instrument with 'hires_j' and it worked fine.

**Comment by smmills** [comment]
If I redirect the Popen latex output from pipe to sdout, I get the following, at which point it hangs:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/MacPorts 2018.47642_7) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./default_results.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 5 language(s) loaded.
(/opt/local/share/texmf-texlive/tex/latex/emulateapj/emulateapj.cls
Document Class: emulateapj 
(/opt/local/share/texmf-texlive/tex/latex/revtex/revtex4-1.cls
Document Class: revtex4-1 2010/07/25/20:33:00 4.1r (http://publish.aps.org/revt
ex4/ for documentation)
ltxutil[2010/07/25/20:33:00 4.1r utilities package (portions licensed from W. E
. Baxter web at superscript.com)]
ltxfront[2010/07/25/20:33:00 4.1r frontmatter package (AO,DPC)]
ltxgrid[2010/07/25/20:33:00 4.1r page grid package (portions licensed from W. E
. Baxter web at superscript.com)]

Class revtex4-1 Warning: No Society specified, using default society aps.

(/opt/local/share/texmf-texlive/tex/latex/revtex/aps4-1.rtx)

Class revtex4-1 Warning: No journal specified, using default pra.


Class revtex4-1 Warning: No type size specified, using default 10.

(/opt/local/share/texmf-texlive/tex/latex/revtex/aps10pt4-1.rtx)
(/opt/local/share/texmf-texlive/tex/latex/textcase/textcase.sty)
(/opt/local/share/texmf-texlive/tex/latex/url/url.sty)
(/opt/local/share/texmf-texlive/tex/latex/natbib/natbib.sty)
(/opt/local/share/texmf-texlive/tex/latex/revtex/revsymb4-1.sty))
(/opt/local/share/texmf-texlive/tex/latex/base/latexsym.sty)
(/opt/local/share/texmf-texlive/tex/latex/graphics/graphicx.sty
(/opt/local/share/texmf-texlive/tex/latex/graphics/keyval.sty)
(/opt/local/share/texmf-texlive/tex/latex/graphics/graphics.sty
(/opt/local/share/texmf-texlive/tex/latex/graphics/trig.sty)
(/opt/local/share/texmf-texlive/tex/latex/graphics-cfg/graphics.cfg)
(/opt/local/share/texmf-texlive/tex/latex/graphics-def/pdftex.def)))
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/amssymb.sty
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/amsfonts.sty))
(/opt/local/share/texmf-texlive/tex/latex/tools/longtable.sty)
(/opt/local/share/texmf-texlive/tex/generic/epsf/epsf.sty
This is `epsf.tex' v2.7.4 <14 February 2011>
)) (/opt/local/share/texmf-texlive/tex/latex/base/textcomp.sty
(/opt/local/share/texmf-texlive/tex/latex/base/ts1enc.def
(/opt/local/share/texmf-texlive/tex/latex/base/ts1enc.dfu)))
(/opt/local/share/texmf-texlive/tex/latex/fancyhdr/fancyhdr.sty)
(/opt/local/share/texmf-texlive/tex/latex/hyperref/hyperref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/hobsub-hyperref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/hobsub-generic.sty))
(/opt/local/share/texmf-texlive/tex/generic/ifxetex/ifxetex.sty)
(/opt/local/share/texmf-texlive/tex/latex/oberdiek/auxhook.sty)
(/opt/local/share/texmf-texlive/tex/latex/oberdiek/kvoptions.sty)
(/opt/local/share/texmf-texlive/tex/latex/hyperref/pd1enc.def)
(/opt/local/share/texmf-texlive/tex/latex/latexconfig/hyperref.cfg))
(/opt/local/share/texmf-texlive/tex/latex/hyperref/hpdftex.def
(/opt/local/share/texmf-texlive/tex/latex/oberdiek/rerunfilecheck.sty))
No file default_results.aux.
(/opt/local/share/texmf-texlive/tex/latex/base/ts1cmr.fd)
(/opt/local/share/texmf-texlive/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/opt/local/share/texmf-texlive/tex/latex/oberdiek/epstopdf-base.sty
(/opt/local/share/texmf-texlive/tex/latex/oberdiek/grfext.sty)
(/opt/local/share/texmf-texlive/tex/latex/latexconfig/epstopdf-sys.cfg))
(/opt/local/share/texmf-texlive/tex/latex/hyperref/nameref.sty
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/gettitlestring.sty))
(/opt/local/share/texmf-texlive/tex/latex/base/ulasy.fd)
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/umsa.fd)
(/opt/local/share/texmf-texlive/tex/latex/amsfonts/umsb.fd)

Package longtable Warning: Column widths have changed
(longtable)                in table 1 on input line 83.


Package longtable Warning: Column widths have changed
(longtable)                in table 2 on input line 108.

! Missing $ inserted.
<inserted text> 
                $
l.125   2455464.86611 & 9.33 & 1.06 & hires_
                                            j \\
? 
```
My .tex file in that neighborhood looks like:
```
110 % Table of RV data
111 \begin{deluxetable}{lrrc}
112 \tablecaption{ Radial Velocities }
113 \tablehead{
114   \colhead{Time} &
115   \colhead{RV} &
116   \colhead{RV Unc.} &
117   \colhead{Inst.} \\
118   \colhead{(JD)} &
119   \colhead{(m s$^{-1}$)} &
120   \colhead{(m s$^{-1}$)} &
121   \colhead{}
122 }
123 \startdata
124 
125   2455464.86611 & 9.33 & 1.06 & hires_j \\
126 
127   2455796.09656 & 3.64 & 1.31 & hires_j \\
128 
129   2455928.72442 & -29.62 & 1.06 & hires_j \\
130 
```

**Comment by bjfultn** [comment]
Ah ok, I see what happened. It's coming from the RV table and mine was being truncated, only printing the 'k' data, which didn't have an underscore. Now I can reproduce your error.

**Comment by smmills** [comment]
Are there any other common characters which which will cause a similar crash?

**Comment by bjfultn** [comment]
Not sure, would anyone in their right mind include a "\" in the instrument name?

**Comment by smmills** [comment]
Do dashes (minus signs) cause problems? E.g., HARPS-N
What about spaces: HIRES J

**Comment by bjfultn** [comment]
Dashes were always ok. 

I could $ that whole column, but then things like dashes render weird.

**Comment by bjfultn** [comment]
this is fixed
