### ISSUE TITLE
import fails without h5py

### ISSUE THREAD

**Issue by mileslucas** [California-Planet-Search/radvel#345]
As noted in https://github.com/nespinoza/juliet/issues/53 `radvel` doesn't install `h5py` within `setup.py` https://github.com/California-Planet-Search/radvel/commit/117d4e6946c73a9b739108da64a891732f9c669b 

This means a clean install (from inside a docker container)
```
$ pip install radvel
```
will fail to import
```python
>>> import radvel
[...]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/radvel/__init__.py", line 16, in <module>
    from .mcmc import *
  File "/usr/local/lib/python3.7/site-packages/radvel/mcmc.py", line 12, in <module>
    import h5py
ModuleNotFoundError: No module named 'h5py'
```

If `h5py` is pip installed, too, import works fine.

**Comment by bjfultn** [comment]
This had to be temporarily removed due to a build problem on ReadTheDocs. They can't install h5py and can't build the docs without it. Once they fix that issue then I'll add it back into the requirements, but for now your solution to install separately is the best we can do. If this is not fixed within a week or two I'll add a note to the install documentation.

**Comment by mileslucas** [comment]
Seems totally reasonable and understandable; thanks for the quick response.
