### ISSUE TITLE
UserDefinedPrior fails (including documentation example)

### ISSUE THREAD

**Issue by parkerholzer** [California-Planet-Search/radvel#346]
I'm working to put a user-defined prior on the eccentricity, but the example given in the documentation for how to do this produces an error. From the traceback, I suspect it has something to do with the TexString argument:

AttributeError: 'str' object has no attribute 'name'

**Comment by bjfultn** [comment]
Could you expand a little on how you are setting this up and provide a more complete traceback?

**Comment by parkerholzer** [comment]
Sure, I open the .py file where the parameterization, optimization starting points, and priors are defined. Then I define the function that returns the density for the user defined prior. (Is this the file where that is supposed to go???)

I did manage to get around the issue by simply adding a class to the priors.py file in the radvel code, keeping the same structure as the other existing classes.

The complete Traceback is as follows though:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/radvel", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/radvel/cli.py", line 197, in main
    args.func(args)
  File "/opt/anaconda3/lib/python3.7/site-packages/radvel/driver.py", line 151, in fit
    post.writeto(postfile)
  File "/opt/anaconda3/lib/python3.7/site-packages/radvel/posterior.py", line 79, in writeto
    pickle.dump(self, f)
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 267, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(x)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 1447, in save_function
    obj.__dict__, fkwdefaults), obj=obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/opt/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py", line 1330, in save_module
    log.info("M2: %s" % obj)
  File "<frozen importlib._bootstrap>", line 286, in _module_repr
  File "<frozen importlib._bootstrap>", line 596, in _module_repr_from_spec
AttributeError: 'str' object has no attribute 'name'

**Comment by bjfultn** [comment]
I'm glad you found a workaround, but I still would like to track this down.

Could you share density function and the line that initializes the prior?

If you have a generally-useful prior that you think should be included with the radvel package I'd be happy to look over a pull request for what you've implemented.

**Comment by ngierty** [comment]
I'm also having a similar User-Defined Prior issue when using the command line to fit a model. I can use the command line fit function just fine but when I try to sample using mcmc I get a pickle error. I've below is my code that's causing the error that uses the example from the docs as a test. I'll try the work-around suggested above.

`
# Libraries and Paths

from math import log, exp
import numpy as np
import matplotlib.pyplot as plt
import radvel
from math import pi
import pandas as pd

# Custom Priors

def trunc_modJeffrey_prior(param_min, param_max, param_0, param):
    if (param_min < param) & (param < param_max):
        prior_param = (param_0*(1+param/param_0)*log(1 + param_max/param_0))**(-1)
        prior_param = log(prior_param)
    else:
        prior_param = -np.inf 
    return prior_param


def trunc_Rayleigh_prior(param_min, param_max, sigma_p, param):
    if (param_min < param) & (param < param_max):
        prior_param = param/(sigma_p**2)/(1 - exp(- param_max**2/(2*sigma_p**2)))
        prior_param = log(prior_param)
    else:
        prior_param = -np.inf
    return prior_param

def K_prior(inp_list):
    return trunc_modJeffrey_prior(0, 999, 1, inp_list[0])


def zeta_prior(inp_list):
   return trunc_Rayleigh_prior(0, 1, 0.2, inp_list[0])

def sigma_prior(inp_list):
    return trunc_modJeffrey_prior(0, 99, 1, inp_list[0])


def myPriorFunc(inp_list):
     if inp_list[0] > 0. and inp_list[0] < 1.:
         return 0.
     else:
         return -np.inf
myTexString = 'Uniform Prior on $\sqrt{e}$'

myPrior = radvel.prior.UserDefinedPrior('e1', myPriorFunc, myTexString)

# Generate the data based on what Nelson (2020) considered reasonable/easy

### Define global planetary system and dataset parameters
nplanets = 1    # number of planets in the system
instnames = ['a'] # list of instrument names. Can be whatever you like (no spaces) but should match 'tel' column in the input file.
ntels = len(instnames)       # number of instruments with unique velocity zero-points
bjd0 = 0
planet_letters = {1: 'b'}   # map the numbers in the Parameters keys to planet letters (for plotting and tables)

### Nelson 2020 parameters for an easily detected planet
np.random.seed(34857)
Q = 200
sigma = 0.6
sigma2_q = 0.9*np.ones(Q)
t = np.random.uniform(low = 0, high = 150, size = Q)
t.sort()
ti = np.linspace(-t.min(),t.max(),400)

params = radvel.Parameters(basis = 'per tp e w k', num_planets = 1, planet_letters=planet_letters)
params['per1'] = radvel.Parameter(value = 42.4) # period
params['tp1'] = radvel.Parameter(value = 2.99) # M_0; radians
params['e1'] = radvel.Parameter(value = 0.04) # zeta
params['w1'] = radvel.Parameter(value = 2) # omega; radians
params['k1'] = radvel.Parameter(value = 2.44) # K; semi-aplitude
params['gamma_a'] = radvel.Parameter(value = 0)
rv_mod = radvel.RVModel(params)
syn_rv = rv_mod(t) + np.random.normal(loc = 0, scale = np.sqrt(sigma**2 + sigma2_q))


#### Put the data in the correct format
data = pd.DataFrame({'time': t, 'mnvel':syn_rv, 'errvel': sigma2_q, 'tel': 'a'})

# Define posterior

### Define prior centers (initial guesses) in a basis of your choice (need not be in the fitting basis)
anybasis_params = radvel.Parameters(nplanets,basis='per tp e w k')    # initialize Parameters object

anybasis_params['per1'] = radvel.Parameter(value = 42.4)
anybasis_params['tp1'] = radvel.Parameter(value = 2.99)
anybasis_params['e1'] = radvel.Parameter(value = 0.04)
anybasis_params['w1'] = radvel.Parameter(value = 2)
anybasis_params['k1'] = radvel.Parameter(value = 2.44)
time_base = 69      # abscissa for slope and curvature terms (should be near mid-point of time baseline)
anybasis_params['gamma_a'] = radvel.Parameter(value = 0)
anybasis_params['dvdt'] = radvel.Parameter(value=0.0)         
anybasis_params['curv'] = radvel.Parameter(value=0.0) 
anybasis_params['jit_a'] = radvel.Parameter(value=0.6) 

### Convert input orbital parameters into the fitting basis
fitting_basis = 'per tc secosw sesinw k'
params = anybasis_params.basis.to_any_basis(anybasis_params,fitting_basis)

params['gamma_a'].vary = False
params['dvdt'].vary = False
params['curv'].vary = False


priors = [
    myPrior,
    #radvel.prior.Jeffreys('per1', 1.25, 1000),
    #radvel.prior.UserDefinedPrior(['k1'], K_prior, 'Modified truncated Jeffreys on K'),
    #radvel.prior.UserDefinedPrior(['e1'], zeta_prior, 'Truncated Raleigh on $\zeta$'),
    #radvel.prior.HardBounds('w1', 0.0, 2*pi),
    #radvel.prior.HardBounds('tp1', 0.0, 2*pi),
    #radvel.prior.UserDefinedPrior(['jit_a'], sigma_prior, 'Modified truncated Jeffreys on $\sigma_J$')
]`
