### ISSUE TITLE
Derive.py does not support a mix of transiting and non-transiting planets

### ISSUE THREAD

**Issue by sealauren** [California-Planet-Search/radvel#36]
Here is my planet dict:
```
# optional argument that can contain planet radii, used for computing densities
planet = dict(
              rp1=3.78, rp_err1=0.38,
#              rp2=7.82, rp_err2=0.72, # planet 2 does not transit
              )
```			  
Here is what happens:
```
unicorn:KOI-142_radvel lweiss$ radvel derive -s KOI-142.py
Multiplying mcmc chains by physical parameters for KOI-142
Derived parameters: ['mpsini1', 'rhop1']
Traceback (most recent call last):
  File "/Users/lweiss/anaconda/bin/radvel", line 9, in <module>
    load_entry_point('radvel-package==0.5b', 'console_scripts', 'radvel')()
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel_package-0.5b-py2.7-macosx-10.6-x86_64.egg/radvel/cli.py", line 142, in main
    args.func(args)
  File "/Users/lweiss/anaconda/lib/python2.7/site-packages/radvel_package-0.5b-py2.7-macosx-10.6-x86_64.egg/radvel/driver.py", line 342, in derive
    loc=P.planet['rp{}'.format(i)], 
KeyError: 'rp2'
```

**Comment by bjfultn** [comment]
This is fixed.
