### ISSUE TITLE
mcmc error - Probability function returned NaN

### ISSUE THREAD

**Issue by aberrico** [California-Planet-Search/radvel#369]
I'm tring to run mcmc using this command:
radvel mcmc -s /path/file.py
And I'm getting this error message:
[========================                          ] 1880000/4000000 (47.0%) steps complete;
Running 2077.06 steps/s; Mean acceptance rate = 16.0%; Min Auto Factor =  17;
Max Auto Relative-Change = 0.0337; Min Tz = 353.4; Max G-R = 1.090
Traceback (most recent call last):
                                    File "/home/adriana/anaconda3/bin/radvel", line 8, in <module>
                                                                                                      sys.exit(main())
                                                                                                                        File "/home/adriana/anaconda3/lib/python3.7/site-packages/radvel/cli.py", line 194, in main
                                      args.func(args)
                                                       File "/home/adriana/anaconda3/lib/python3.7/site-packages/radvel/driver.py", line 198, in mcmc
                                                                                                                                                         savename=backend_loc, proceed=args.proceed, proceedname=backend_loc)
                                              File "/home/adriana/anaconda3/lib/python3.7/site-packages/radvel/mcmc.py", line 363, in mcmc
                                                                                                                                              for sample in sampler.sample(p1, store=True):
            File "/home/adriana/anaconda3/lib/python3.7/site-packages/emcee-3.0.2-py3.7.egg/emcee/ensemble.py", line 343, in sample
                                                                                                                                       state, accepted = move.propose(model, state)
    File "/home/adriana/anaconda3/lib/python3.7/site-packages/emcee-3.0.2-py3.7.egg/emcee/moves/red_blue.py", line 93, in propose
                                                                                                                                     new_log_probs, new_blobs = model.compute_log_prob_fn(q)
             File "/home/adriana/anaconda3/lib/python3.7/site-packages/emcee-3.0.2-py3.7.egg/emcee/ensemble.py", line 456, in compute_log_prob
                                                                                                                                                  raise ValueError("Probability function returned NaN")
                      ValueError: Probability function returned NaN

**Comment by bjfultn** [comment]
This usually happens when your fit is poorly constrained or your starting guesses for parameters are outside or near the boundaries of priors.
