### ISSUE TITLE
error obtained while running MAP fit 

### ISSUE THREAD

**Issue by Hiyabiswas** [California-Planet-Search/radvel#379]
whenever, I run this command: radvel fit -s /home/sbiswas/radvel-master/example_planets/HD164922.py, I found no error, it works fine. But whenever I run this command: radvel fit -s /home/sbiswas/radvel-master/example_planets/try_final.py, for my data file, this below mentioned error comes:
(base) [sbiswas@fedora ~]$ radvel fit -s /home/sbiswas/radvel-master/example_planets/try_final.py 
/home/sbiswas/radvel-master/example_planets/try_final.py
Performing maximum a posteriori fitting for try_final
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/bin/radvel", line 33, in <module>
    sys.exit(load_entry_point('radvel==1.4.9', 'console_scripts', 'radvel')())
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/cli.py", line 197, in main
    args.func(args)
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/driver.py", line 146, in fit
    P, post = radvel.utils.initialize_posterior(config_file, decorr=args.decorr)
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/utils.py", line 137, in initialize_posterior
    like = radvel.likelihood.CompositeLikelihood(list(likes.values()))
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/likelihood.py", line 257, in __init__
    self.y = np.append(self.y, like.y - like.vector.vector[like.vector.indices[like.gamma_param]][0])
TypeError: unsupported operand type(s) for -: 'str' and 'float'

**Comment by bjfultn** [comment]
resolved over email. There were hyphens in place of minus signs in the data file.
