### ISSUE TITLE
AttributeError: 'str' object has no attribute '_uninitialized_submodules'

### ISSUE THREAD

**Issue by SilencePhyxion** [California-Planet-Search/radvel#387]
Hi there,

I've been wanting to install radvel in a new conda environment but I have come across this weird error when I start the tutorials.

```
`(RV) C:\Users\USER\Desktop\Workspace\Exoplanet>radvel --help
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\USER\anaconda3\envs\RV\Scripts\radvel.exe\__main__.py", line 4, in <module>

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1145, in _find_and_load_unlocked

AttributeError: 'str' object has no attribute '_uninitialized_submodules'
```
`

I've followed the installation guide (installing celerite and tex), but I fear text might be the issue as it is not showing in my system path. Is there anything I am doing wrong?

Thanks in advance!

**Comment by SilencePhyxion** [comment]
I should include that I have installed rvsearch, and upon testing rvsearch --help, that works. But why does radvel --help doesn't?

**Comment by SilencePhyxion** [comment]
It seems a change in python environment to version 3.11.0 was required, as well as a fresh reinstall. It works now!
