### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#54]
@howardisaacson: re-posting your question:

```
This is my current error I receive when running radvel locally.
bash-3.2$ radvel fit -s example_data/HD164922.py 
example_data/HD164922.py
Performing max-likelihood fitting for HD164922
Traceback (most recent call last):
  File "/usr/local/bin/radvel", line 11, in <module>
    load_entry_point('radvel-package==0.7.1', 'console_scripts', 'radvel')()
  File "/usr/local/lib/python2.7/site-packages/radvel/cli.py", line 134, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/radvel/driver.py", line 93, in fit
    P, post = radvel.utils.initialize_posterior(config_file)
  File "/usr/local/lib/python2.7/site-packages/radvel/utils.py", line 15, in initialize_posterior
    P = imp.load_source(system_name, os.path.abspath(config_file))
  File "/Users/howard/cps/radvel/example_data/HD164922.py", line 1
    time mnvel errvel tel svalue
             ^
SyntaxError: invalid syntax
```

**Comment by petigura** [comment]
Can you verify that you are on commit:

910791aae296f88806e483d341f71679fffb914d

HD1649222.py should be in the example_planets/ directory. This make me wonder if you are on an old version of the code.

Here's how I run the example:

```
[radvel]$ radvel fit -s example_planets/HD164922.py
example_planets/HD164922.py
Performing max-likelihood fitting for HD164922
Initial loglikelihood = -1184.115772
Performing maximum likelihood fit...
Final loglikelihood = -992.850065
Best-fit parameters:
parameter                     value      vary
curv                              0      False
dvdt                              0      False
e1                         0.122116           
e2                          0.24019           
gamma_a                     1.07579       True
gamma_j                    0.182262       True
gamma_k                    0.176783       True
jit_a                      0.989035       True
jit_j                       2.89472       True
jit_k                       2.49965       True
k1                          7.20149           
k2                          2.19876           
logk1                       1.97429       True
logk2                      0.787892       True
per1                        1200.74       True
per2                        75.7407       True
secosw1                   -0.273155       True
secosw2                  -0.0871177       True
sesinw1                     0.21795       True
sesinw2                    0.482287       True
tc1                         6784.44       True
tc2                         6277.92       True
tp1                         6921.48           
tp2                          6279.2           
w1                          2.46813           
w2                           1.7495           

Priors
------
e1 constrained to be < 0.99
e2 constrained to be < 0.99
Gaussian prior on tc1, mu=2456779.0, sigma=300.0
Bounded prior on jit_k, min=0.0, max=10.0
Bounded prior on jit_j, min=0.0, max=10.0
Bounded prior on jit_a, min=0.0, max=10.0
```

**Comment by howardisaacson** [comment]
I confirm that I am on the right branch. I ran $ pip install . --upgrade   when in stalling. This is my current error:

bash-3.2$ radvel fit -s example_planets/HD164922.py 
WARNING: KEPLER: Unable to import C-based Kepler'sequation solver. Falling back to the slower NumPy implementation.
example_planets/HD164922.py
Performing max-likelihood fitting for HD164922
Traceback (most recent call last):
  File "/usr/local/bin/radvel", line 11, in <module>
    load_entry_point('radvel-package==0.7.1', 'console_scripts', 'radvel')()
  File "/Users/howard/cps/radvel/radvel/cli.py", line 134, in main
    args.func(args)
  File "/Users/howard/cps/radvel/radvel/driver.py", line 93, in fit
    P, post = radvel.utils.initialize_posterior(config_file)
  File "/Users/howard/cps/radvel/radvel/utils.py", line 15, in initialize_posterior
    P = imp.load_source(system_name, os.path.abspath(config_file))
  File "/Users/howard/cps/radvel/example_planets/HD164922.py", line 46, in <module>
    data = pd.read_csv(os.path.join(radvel.DATADIR,'164922_fixed.txt'), sep=' ')
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 529, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 295, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 612, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 747, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1119, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
IOError: File /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/radvel_example_data/164922_fixed.txt does not exist

**Comment by bjfultn** [comment]
Did it give any errors about permissions when you installed? I wonder if your user account doesn't have write access to that directory `/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/`

**Comment by petigura** [comment]
Solution: fresh install anaconda.

**Comment by Hiyabiswas** [comment]
while performing MCMC in radvel, I found this error:

radvel mcmc -s /home/sbiswas/radvel-master/example_planets/HD164922.py
WARNING: KEPLER: Unable to import C-based Kepler'sequation solver. Falling back to the slower NumPy implementation.
/home/sbiswas/radvel-master/example_planets/HD164922.py
Loading starting positions from previous MAP fit
Running MCMC for HD164922, N_walkers = 50, N_steps = 10000, N_ensembles = 8, Min Auto Factor = 40, 
Max Auto Relative-Change = 0.03, Max G-R = 1.01, Min Tz = 1000 ...
Traceback (most recent call last):
  File "/home/sbiswas/.local/bin/radvel", line 33, in <module>
    sys.exit(load_entry_point('radvel==1.4.9', 'console_scripts', 'radvel')())
  File "/home/sbiswas/.local/lib/python3.10/site-packages/radvel/cli.py", line 197, in main
    args.func(args)
  File "/home/sbiswas/.local/lib/python3.10/site-packages/radvel/driver.py", line 197, in mcmc
    chains = radvel.mcmc(post, nwalkers=args.nwalkers, nrun=args.nsteps, ensembles=args.ensembles,
  File "/home/sbiswas/.local/lib/python3.10/site-packages/radvel/mcmc.py", line 267, in mcmc
    np_info = np.__config__.blas_opt_info
AttributeError: module 'numpy.__config__' has no attribute 'blas_opt_info'

Can anyone help me regarding this?

**Comment by bjfultn** [comment]
Try downgrading to numpy 1.20.3. https://stackoverflow.com/questions/70839312/module-numpy-distutils-config-has-no-attribute-blas-opt-info

**Comment by Hiyabiswas** [comment]
Thank you Sir.

**Comment by Hiyabiswas** [comment]
This is my current error I receive when running radvel.
(base) [sbiswas@fedora ~]$ radvel fit -s /home/sbiswas/radvel-master/example_planets/try_final.py 
/home/sbiswas/radvel-master/example_planets/try_final.py
Performing maximum a posteriori fitting for try_final
Traceback (most recent call last):
  File "/home/sbiswas/anaconda3/bin/radvel", line 33, in <module>
    sys.exit(load_entry_point('radvel==1.4.9', 'console_scripts', 'radvel')())
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/cli.py", line 197, in main
    args.func(args)
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/driver.py", line 146, in fit
    P, post = radvel.utils.initialize_posterior(config_file, decorr=args.decorr)
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/utils.py", line 137, in initialize_posterior
    like = radvel.likelihood.CompositeLikelihood(list(likes.values()))
  File "/home/sbiswas/anaconda3/lib/python3.10/site-packages/radvel/likelihood.py", line 257, in __init__
    self.y = np.append(self.y, like.y - like.vector.vector[like.vector.indices[like.gamma_param]][0])
TypeError: unsupported operand type(s) for -: 'str' and 'float'
