### ISSUE TITLE
Error installing with Python 3

### ISSUE THREAD

**Issue by RogueAstro** [California-Planet-Search/radvel#68]
I got the following error when I tried to install ``radvel`` in my Mac using ``pip`` in Python 3:

    Collecting pp==1.6.5 (from radvel)
    Downloading pp-1.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/pk/0vpc4skx7j57cc1zlk2b2jjw0000gn/T/pip-build-xpdaeu_l/pp/setup.py", line 12, in <module>
        from pp import version as VERSION
      File "/private/var/folders/pk/0vpc4skx7j57cc1zlk2b2jjw0000gn/T/pip-build-xpdaeu_l/pp/pp.py", line 121
        print sout,
                 ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by bjfultn** [comment]
Unfortunately, RadVel does not support Python 3.
