### ISSUE TITLE
RVParamters Issue from Griet Van de Steene

### ISSUE THREAD

**Issue by bjfultn** [California-Planet-Search/radvel#96]
Copy of an e-mail from my website:

I installed radvel without problem today, 
but when I tested it I got the following error:
```
radvel fit -s /home/gsteene/radvel/example_planets/HD164922.py
/home/gsteene/radvel/example_planets/HD164922.py
Performing max-likelihood fitting for HD164922
Traceback (most recent call last):
 File "/usr/local/bin/radvel", line 11, in <module>
   sys.exit(main())
 File "/usr/local/lib/python2.7/dist-packages/radvel/cli.py", line 158, in main
   args.func(args)
 File "/usr/local/lib/python2.7/dist-packages/radvel/driver.py", line 101, in fit
   P, post = radvel.utils.initialize_posterior(config_file, decorr=args.decorr)
 File "/usr/local/lib/python2.7/dist-packages/radvel/utils.py", line 15, in initialize_posterior
   P = imp.load_source(system_name, os.path.abspath(config_file))
 File "/home/gsteene/radvel/example_planets/HD164922.py", line 19, in <module>
   params = radvel.RVParameters(nplanets,basis='per tc e w k', planet_letters=planet_letters)    # initialize RVparameters object
```

**Comment by sblunt** [comment]
Looks like the user just didn't update the config files.

**Comment by bjfultn** [comment]
I agree, I sent an e-mail in reply to have him clone the repo again.

The larger issue is that this directory gets placed somewhere deep in the system's Python path when using `pip` to install so it may not be easy for users to locate those example config files if they don't clone from the repo. I'm not sure how to get around that. Maybe I can add a default search path for the config files such that it looks in the install location first if a full path is not given.

**Comment by sblunt** [comment]
Got it.

**Comment by bjfultn** [comment]
```
Dear Mr Fulton,

I did the installation the easiest way using pip as mentioned on the document webpage, with sudo. I exactly followed this:
http://radvel.readthedocs.io/en/latest/quickstartcli.html#installation

As you said, I copied the files to the /home/gsteene/radvel, but keep on getting issues with paths, and  I don't really know
how to tell radvel to look in the correct dir.

It seems to go wrong in cli.py line 158

It looks for /usr/radvel_example_data/164922_fixed.txt
instead of in /home/gsteene/radvel/example_data/
where the file does exist.


radvel fit -s /home/gsteene/radvel/example_planets/HD164922.py
/home/gsteene/radvel/example_planets/HD164922.py
Performing max-likelihood fitting for HD164922
Traceback (most recent call last):
 File "/usr/local/bin/radvel", line 11, in <module>
   sys.exit(main())
 File "/usr/local/lib/python2.7/dist-packages/radvel/cli.py", line 158, in main
   args.func(args)
 File "/usr/local/lib/python2.7/dist-packages/radvel/driver.py", line 101, in fit
   P, post = radvel.utils.initialize_posterior(config_file, decorr=args.decorr)
 File "/usr/local/lib/python2.7/dist-packages/radvel/utils.py", line 15, in initialize_posterior
   P = imp.load_source(system_name, os.path.abspath(config_file))
 File "/home/gsteene/radvel/example_planets/HD164922.py", line 58, in <module>
   data = pd.read_csv(os.path.join(radvel.DATADIR,'164922_fixed.txt'), sep=' ')
 File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 705, in parser_f
   return _read(filepath_or_buffer, kwds)
 File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 445, in _read
   parser = TextFileReader(filepath_or_buffer, **kwds)
 File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 814, in __init__
   self._make_engine(self.engine)
 File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1045, in _make_engine
   self._engine = CParserWrapper(self.f, **self.options)
 File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1684, in __init__
   self._reader = parsers.TextReader(src, **kwds)
 File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
 File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /usr/radvel_example_data/164922_fixed.txt does not exist

Cheers

Griet
```

**Comment by bjfultn** [comment]
```
Hi Griet,

Pip should have installed that example data directory somewhere in your system’s path. This may have gone awry since it looks like you are using your system’s version of python and not a third party distribution (e.g. anaconda python). Perhaps it uses an old version of pip.

Ok, lets just try to duplicate and edit a copy of that example configuration file (HD164922.py). You can put the copy anywhere you like on your machine.

In the duplicate file edit line 58 to point to the place where you know where the file radvel_example_data/164922_fixed.txt exists. Replace "os.path.join(radvel.DATADIR,'164922_fixed.txt’)” with the correct full path to that file.

Now run radvel pointing to this duplicate configuration file. Make sure you don’t run radvel from within the /home/gsteene/radvel directory. Let me know what happens.


Thanks,
BJ
```

**Comment by bjfultn** [comment]
```
Dear BJ,

I have tried to install anaconda, but afterwards all my paths are messed up and nothing works anymore. So I gave up anaconda on this PC.
I do update pip almost every time before installing something.

I went through all the commands in example fit and optional features without any problem !

I did download the code to get the latest version
and put it in my home bin dir which is in my path,
and changed the line you suggested.

radvel.DATADIR = '/home/gsteene/bin/radvel-master/example_data/'
data = pd.read_csv(os.path.join(radvel.DATADIR,'164922_fixed.txt'), sep=' ')

It may be overexplicit now, but I went through ALL the commands in example fit and optional features without any problem !

I can move to the next step.

Thanks a lot !

Griet
```
